//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using DHTMLX.Scheduler;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EventBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventBooking()
        {
            this.Participants = new HashSet<Participant>();
        }


        [DHXJson(Alias = "Event_ID")]
        
        public int Event_ID { get; set; }


        [Required]
        [DHXJson(Alias = "Event_Name")]
        [Display(Name = "Event Name")]
        public string Event_Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> Start_Date { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> End_Date { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = "Invalid EventName")]
        [Display(Name = "Number of Participants")]
        public Nullable<int> No_Of_Participants { get; set; }
        public Nullable<int> Pay_Event_BookingID { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public string servicetypeid { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string EventTypeID { get; set; }
        public string Service_Company_ID { get; set; }

        [DHXJson(Alias = "Text")]
        public string Descriptions { get; set; }
        public string EventType { get; set; }
        public string Venue { get; set; }
        public string FoodCompany { get; set; }
        [Display(Name = "Equipment Company")]
        public string ElectricalCompany { get; set; }
    
        public virtual payment_Booking payment_Booking { get; set; }
        public virtual EventType EventType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual service_company service_company { get; set; }
        public virtual serviceType serviceType { get; set; }
        public virtual Venue Venue1 { get; set; }
    }
}
