//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Vgather.Models
{
    internal class ValidateFileAttribute : Attribute
    {
        public string ErrorMessage { get; set; }
    }
}